### ISSUE TITLE
"guys" is gender nuetral

### ISSUE THREAD

**Issue by Wolfhound905** [silasary/iwazaru_bot#188]

**Comment by mastercoms** [comment]
Is a straight guy attracted to guys?

**Comment by silasary** [comment]
There are enough people who find the term uncomfortable that it's generally considered a Microaggression.

Whether they're uncomfortable enough to confront you about your word choice is a different question (usually it's not worth it, because you're likely to get defensive and double-down)

This exact interaction, over this exact phrase is precisely why I made the bot in the first place.  Because even though my friends acknowledge that I feel excluded whenever they ask if the guys want to do something, they frequently forget, and I found it too exhausting to remind them a dozen times a day.
